# Hangman programes makefile

hangman: hangman.c
	gcc -Wall -pedantic -std=c11 -o hangman hangman.c
	echo Hangman program complied successfully

# This is just a shortcut that will remove out binaries
.PHONY: clean
clean:
	rm hangman
